### ISSUE TITLE
articles/*ブランチのプルリクに紐づいたArticles Branch CIが走らない

### ISSUE THREAD

**Issue by oka4shi** [WORD-COINS/article-template-typst#16]
現在のarticles_branch.yamlは、
```yml
on:
  push:
    branches: ["articles/**"]
  pull_request:
    branches: ["articles/**"]
```
となっているが、[on.pull_request.branchesは「特定のブランチを**対象とする** pull request 」に対して実行される](https://docs.github.com/ja/actions/writing-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore)ため、この書き方だと「arcicles/**」ブランチに向かって投げたプルリクエストに対して走る設定となってしまっていて意図する挙動と異なる。

また、`BRANCH="${GITHUB_REF#refs/heads/}"`でブランチ名が取れるのはpushの場合のみで、pull_requestの場合は`BRANCH: ${{ github.head_ref }}`と書く必要がある。

実はプルリクエストのブランチにコミットが追加されるたびにon.pull_requestは走るので、以下のように直してしまうのがいいのではないかと思う。

```yml
name: Articles Branch CI

on:
  pull_request:
    branches: ["main"]

jobs:
  make-article:
    runs-on: ubuntu-24.04
    if: startsWith(github.head_ref, 'articles/')

（略）
```

参考: [特定のブランチ名のプルリクエストで動作するGitHub Actionsを作る](https://zenn.dev/ryo_kawamata/articles/github-actions-specific-branch)
